# Generated by Django 5.0.7 on 2024-07-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='manufacturer',
            new_name='company',
        ),
    ]
