# Generated by Django 5.0.7 on 2024-07-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_manufacturer_carmodel_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='company',
            new_name='manufacturer',
        ),
    ]
