# Generated by Django 5.0.7 on 2024-08-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_company_carmodel_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
